<?php

use App\Controller\ProfileController;

/**
 * @var string $section
 * @var \App\Entity\User $user
 * @var \App\Entity\UserContact $contact
 * @var \Zend\Form\Form $form
 * @var \App\Form\SaveResult $saveResult
 */
?>

  <div class="row">
    <div class="col-md-3">
      <div class="well">
        <h3>//@TODO user personal menu</h3>
      </div>
    </div>
    <div class="col-md-7">
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="profile_<?=$section;?>">
          <div class="well no-padding">
            <div class="page_block_header"><?=$this->translate(ProfileController::SECTION_NAMES[$section]); ?></div>
            <?php if(isset($saveResult)): ?>
              <?=$this->saveResult($saveResult);?>
            <?php endif; ?>
            <?php
            /** @var \App\View\Helper\MaterialForm $materialForm */
            $materialForm = $this->materialForm();
            $materialForm->setElementAsCol(true)->render($form);
            ?>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-2">
      <div class="well no-padding">
        <ul class="nav nav-pills nav-stacked">
          <li role="presentation" class="<?=($section != ProfileController::SECTION_MAIN) ?: 'active'; ?>">
            <a
                href="<?=$section == ProfileController::SECTION_MAIN ? ('#profile_' . $section) : $this->url('profile', ['action' => 'edit', 'section' => ProfileController::SECTION_MAIN]); ?>"
                <?=($section != ProfileController::SECTION_MAIN) ?: 'aria-controls="profile" role="tab" data-toggle="tab"'; ?>
            >
              <?=$this->translate(ProfileController::SECTION_NAMES[ProfileController::SECTION_MAIN]); ?>
            </a>
          </li>
          <li role="presentation" class="<?=($section != ProfileController::SECTION_CONTACTS) ?: 'active'; ?>">
            <a
                href="<?=$section == ProfileController::SECTION_CONTACTS ? ('#profile_' . $section) : $this->url('profile', ['action' => 'edit', 'section' => ProfileController::SECTION_CONTACTS]); ?>"
                <?=($section != ProfileController::SECTION_CONTACTS) ?: 'aria-controls="profile" role="tab" data-toggle="tab"'; ?>
            >
              <?=$this->translate(ProfileController::SECTION_NAMES[ProfileController::SECTION_CONTACTS]); ?>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>

<?php if ($section == ProfileController::SECTION_MAIN): ?>
  <?php
  /** @var \Zend\View\Helper\HeadScript $hs */
  $hs = $this->headScript();
  $hs->prependFile($this->basePath('js/profile/edit.js'), null, ['async' => 'async', 'defer' => 'defer']);
  ?>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAXIws9brfybSXlQkilO0Sxw6kxa5FirbA&signed_in=true&libraries=places&callback=initAutocomplete"
          async defer></script>
<?php endif; ?>