<?php
if ($this->ZfbUserIdentity()) {
  echo "Hi, " . $this->ZfbUserDisplayName() . "!";
  echo "<a href='".$this->url('zfbuser', ['action' => 'logout'])."'>Logout</a>";
} else {
  echo $this->zfbUserAuthenticationWidget(['render' => true, 'redirect' => 'home']);
}
?>
<div class="jumbotron">
  <h1>Jumbotron</h1>

  <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>

  <p><a class="btn btn-primary btn-lg">Learn more</a></p>
</div>
<div class="jumbotron">
  App::index
</div>
<div class="jumbotron">
  App::index
</div>
<div class="jumbotron">
  App::index
</div>
<div class="jumbotron">
  App::index
</div>
<div class="jumbotron">
  App::index
</div>
<div class="jumbotron">
  App::index
</div>
<div class="jumbotron">
  App::index
</div>