<?php
/**
 * @var \App\Entity\User $user
 */
?>
<div id="crop-avatar">
    <div class="avatar-view" title="Change the avatar">
        <img src="<?=$this->userAvatar($user, 'large'); ?>" alt="<?=$user->getDisplayName(); ?>">
    </div>

    <!-- Cropping modal -->
    <div class="modal fade" id="avatar-modal" aria-hidden="true" aria-labelledby="avatar-modal-label" role="dialog" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <form class="avatar-form" action="<?=$this->url('profile', ['action' => 'saveAvatar']); ?>" enctype="multipart/form-data" method="post">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title" id="avatar-modal-label">Change Avatar</h4>
                    </div>
                    <div class="modal-body">
                        <div class="avatar-body">

                            <!-- Upload image and data -->
                            <div class="avatar-upload">
                                <input type="hidden" class="avatar-src" name="avatar_src">
                                <input type="hidden" class="avatar-data" name="avatar_data">
                            </div>

                            <!-- Crop and preview -->
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="avatar-wrapper"></div>
                                </div>
                                <div class="col-md-3">
                                    <div class="avatar-preview preview-lg"></div>
                                    <div class="avatar-preview preview-md"></div>
                                    <div class="avatar-preview preview-sm"></div>
                                </div>
                            </div>

                            <div class="row avatar-buttons">
                                <div class="col-md-9">
                                    <label class="btn btn-primary btn-upload" for="avatarInput" title="<?=$this->translate('Choose a file'); ?>" data-toggle="tooltip">
                                        <input type="file" class="sr-only avatar-input" id="avatarInput" name="avatar_file" accept="image/*">
                                        <span>
                      <span class="fa fa-upload"></span> <?=$this->translate('Choose a file'); ?>
                    </span>
                                    </label>
                                </div>
                                <div class="col-md-3">
                                    <button type="submit" class="btn btn-primary btn-block avatar-save">Done</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--<div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>-->
                </form>
            </div>
        </div>
    </div><!-- /.modal -->
    <!-- Loading state -->
    <div class="loading" aria-label="Loading" role="img" tabindex="-1"></div>
</div>
